### ISSUE TITLE
메인페이지 화면 개발

### ISSUE THREAD

**Issue by ap9407** [2Jo-Logistics-Management/smart-logistics-front#24]
// 해당 이슈에 대해 간략하게 설명 해 주세요.
## Overview

- 발주 state 그래프 만들기
- 창고 top5 도너츠그래프 만들기
- 발주 입고 카운트 막대 그래프 만들기

---

// 이슈에서 할 일에 대해 간략하게 설명 해 주세요.
## To-Do

- [ ] 발주 준비, 진행, 완료 그래프 만들기
- [ ] 창고 top5 도너츠 그래프 만들기
- [ ] 발주 카운트, 입고 카운트 막대 그래프 만들기

---

// 이슈 해결에 참조한 링크가 있다면 작성 해 주세요.
### Reference

> 참조 자료 및 링크
> `[참조한 링크](홈페이지 명을 입력 해 주세요.)`
