### ISSUE TITLE
입고 페이지 수정

### ISSUE THREAD

**Issue by Ozini08** [2Jo-Logistics-Management/smart-logistics-front#47]
## Overview
- 입고 부분 css 수정

---

## To-Do

- [ ] 입고 메인(ReceiveComponenets) css 수정
- [ ] 발주적용(입고등록- ReceiveModal) 모달 css 수정
- [ ] 입고 메인 디테일, 추가부분 (ReceiveComponenets2) css 수정

---

### Reference

> 참조 자료 및 링크
> `[참조한 링크](홈페이지 명을 입력 해 주세요.)`
